### ISSUE TITLE
Need to check that everything important is logged

### ISSUE THREAD

**Issue by oisinq** [charliekelly13/COMP47660#73]
Based off her list at the very least.

> Ensure that the following operations are logged: user logins, payment of fees, modification of the information about a module. --> suggested in the report

**Comment by oisinq** [comment]
This looks good to me: https://stackoverflow.com/questions/11456774/spring-security-authentication-logging

**Comment by DarraghClarke** [comment]
Gave a run through the code there
-Payment of fees are logged as of #74
-Editing modules are logged
-login attempts are logged as of #74
